import { Header } from '@/components/Header';
// import { SessionProvider } from '@/components/SessionProvider';
import type { Metadata } from 'next';
import './globals.css';
import { ReactNode } from 'react';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

interface RootLayoutProps {
    children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
    return (
        <html lang="kr">
            <body className="bg-gray-100">
                {/* <SessionProvider> */}
                <Header />
                <main className="flex flex-col items-center justify-start min-h-screen pt-[70px] w-full">
                    {children}
                </main>
                {/* </SessionProvider> */}
            </body>
        </html>
    );
}
