import Header from '@/components/header';
import SessionProvider from '@/components/SessionProvider';
import type { Metadata } from 'next';
import './globals.css';
import { ReactNode } from 'react';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

interface RootLayoutProps {
    children: ReactNode;
}

const RootLayout = ({ children }: RootLayoutProps) => {
    return (
        <html lang="kr">
            <body>
                <SessionProvider>
                    <Header />
                    <main>{children}</main>
                </SessionProvider>
            </body>
        </html>
    );
};
export default RootLayout;
